Qovery/Replibyte

README.md
TRANSFORMERS.md
replibyte/src/config.rs
replibyte/src/transformer/email.rs
replibyte/src/transformer/mod.rs

Hi @evoxmusic 
I thought an email transformer would be a good idea, there are often a need to remove real email addresses from production databases. So here is a pull request. 
I've added some tests but there is some tests which failed because i'm missing some environment variables like `AWS_ACCESS_KEY_ID` ...
Maybe I could setup a [minio server](https://min.io/) or another open source S3 compatible solution inside docker-compose.yml, I could do that in another pull request ?

feat: add an email transformer

---

replibyte/src/cli.rs

Hello
There is a typo in the description in the transformer subcommand
```
./target/debug/replibyte -c ./examples/source-postgres-bridge-minio.yaml transformer
...
SUBCOMMANDS:
help    Print this message or the help of the given subcommand(s)
list    list available backups
```
It displays `backup` instead of `transformers`
This PR changes the description

fix: typo in transformer list description subcommand

---

TRANSFORMERS.md
replibyte/src/config.rs
replibyte/src/transformer/mod.rs
replibyte/src/transformer/redacted.rs

@evoxmusic 
A new `redacted` transformer  (strings only), it adds 10 `*` for string longer than 3 characters. 
"a" -> "a"
"abc" -> "abc"
"abcd" -> "abc**********"
"4242 4242 4242 4242" -> "424**********"
In a future PR, we could add options to change the default "*" character, keeping the same length or the number of characters to remain visible. 
If the default behavior seems right for you, you're free to merge

Base redacted transformer

---

Cargo.lock
replibyte/Cargo.toml
replibyte/src/config.rs
replibyte/src/destination/mongodb.rs
replibyte/src/main.rs
replibyte/src/source/mongodb.rs

Hi @evoxmusic 
This PR add support for the authSource parameter in mongo connection string. It was set as "admin" during `mongodump` and `mongorestore` commands.  The default remains the `admin` database as it's the default in MongoDB.
Later we could still improve by supporting other options as tls, ... in connection uri for Mongo and Postgres.
I also add a connection status check in the source init. (the same as in the destination init)
Before:
```
➜  replibyte git:(add-mongo-auth-db) ✗ 2022-04-02T15:59:50.181+0200	Failed: I/O failure reading beginning of archive: EOF
2022-04-02T15:59:50.181+0200	0 document(s) restored successfully. 0 document(s) failed to restore.
```
Now:
```
➜  replibyte git:(add-mongo-auth-db) ✗ ./target/debug/replibyte -c …
```

feat: add mongo auth db

---

README.md

This is a required parameter and doesn't work without this.

chore: mention `region` parameter in example of the configuration file

---

replibyte/src/destination/postgres_docker.rs
replibyte/src/main.rs

Wrong credentials was printed when the container was starting. Let me know if it works for you now @evoxmusic 
This is the corrected command output:
```sh
cargo run -- -c ./examples/source-postgres-bridge-minio.yaml restore local -v latest --image postgres --port 5433
To connect to your Postgres database, use the following connection string:
> postgres://postgres:password@localhost:5433/postgres
Waiting for Ctrl-C to stop the container
```
```sh
PGPASSWORD=password psql -h localhost -p 5433 -U postgres -d postgres
psql (14.2, server 13beta3 (Debian 13~beta3-1.pgdg100+1))
Type "help" for help.
postgres=# \dt+
List of relations
Schema |          Name          | Type  |  Owner   | Persistence | Access method |    Size    | Description …
```

fix: print correct connection string when restoring in a local Postgres container

---

README.md
examples/replibyte.yaml
examples/source-postgres-bridge-minio.yaml
examples/with-encryption.yaml
replibyte/src/bridge/mod.rs
replibyte/src/bridge/s3.rs
replibyte/src/commands/backup.rs
replibyte/src/commands/restore.rs
replibyte/src/config.rs
replibyte/src/main.rs
replibyte/src/telemetry.rs

This PR closes #53
Compression and encryption was always override by the `destination` section in the config file. https://github.com/Qovery/replibyte/compare/main...fabriceclementz:fix-encryption?expand=1#diff-70dba71af950fe9043b343b216d6e7d1a9e8b1c85b06bbc8b060aad5111e887fL86
For the restore commands, it makes sense to check if the backup is compressed and encrypted directly from the backup manifest and not from the config file. This PR removes the encryption_key and compression option in the destination config.
The encryption key is always read from the source configuration. As the encryption key needs to be the same when encrypting or decrypting, we could add the encryption_key at the top level of the yaml file too ? WDYT @evoxmusic

fix: cli parsing for compression and encryption parameters

---

.github/workflows/on-release.yml

After much trial and error, I was finally succesful in fixing our release pipeline.
I have tested it in my local fork, and it seems like it's working.
The new pipeline is a combination of: 
- [copying some code from our old release action](https://github.com/rust-build/rust-build.action/blob/master/entrypoint.sh#L85)
- [a different, more generic release action](https://github.com/softprops/action-gh-release) 
- [a great docker image](https://github.com/joseluisq/rust-linux-darwin-builder)
-  and some improvisations :)
Note: the git history was really messy in this one, since to trigger the release action I always had to commit + push + release in my fork. Therefore, I squashed all the commits into one single commit to make it tidier.

fix: release pipeline for macOS

---

replibyte/src/bridge/mod.rs
replibyte/src/bridge/s3.rs
replibyte/src/cli.rs
replibyte/src/main.rs

Hi @evoxmusic 
This PR adds a `--name` option to the `backup run` command as we discuss in #67.
Close #67

feat: add an option to name the backup

---

docker-compose-dev.yml
docker-compose-mysql-minio.yml
docker-compose-mysql.yml

Hi @evoxmusic  @benny-n 
As we discussed on Discord, this PR fix the healthcheck command for MySQL containers
```sh
> docker-compose -f "docker-compose-mysql-minio.yml" up -d
> docker ps
CONTAINER ID   IMAGE                                      COMMAND                  CREATED         STATUS                   PORTS                               NAMES
1aba86152c1c   mysql:8                                    "docker-entrypoint.s…"   4 minutes ago   Up 4 minutes (healthy)   33060/tcp, 0.0.0.0:3307->3306/tcp   replibyte_dest-mysql_1
556794c50301   minio/minio:RELEASE.2022-03-17T06-34-49Z   "/usr/bin/docker-ent…"   4 minutes ago   Up 4 minutes (healthy)   0.0.0.0:9000-9001->9000-9001/tcp    replibyte_bridge-minio_1
3c6855bb7c07   mysql:8 …
```

fix: make the MySQL container healthy by fixing the healthcheck command

---

replibyte/src/destination/mongodb.rs
replibyte/src/destination/mysql.rs
replibyte/src/destination/postgres.rs
replibyte/src/source/mod.rs
replibyte/src/source/mongodb.rs
replibyte/src/source/mysql.rs
replibyte/src/source/postgres.rs
replibyte/src/tasks/full_backup.rs
replibyte/src/utils.rs

Hi @evoxmusic 
To resolve #71 and give more context to RepliByte users, I've removed `panic` calls and propagates errors in the full backup task.
Then I've printed the stderr output for all the dump ("pg_dump", "mysqldump", "mongodump") commands which render like this 
```sh
replibyte -c ./examples/source-mysql-bridge-minio.yaml --no-telemetry backup run`
⠒ [00:00:00] [----------------------------------------------------------------------------------------------------------------------------------------] 0B/100.00MiB (0s)
command error: mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Got error: 1045: Access denied for user 'root'@'172.18.0.1' (using password: YES) when trying to connect
```
Feedback welcome if you think of another solution. …

fix: add error handling for backup run command

---

dump-parser/src/mysql/mod.rs
dump-parser/src/postgres/mod.rs

As discussed in discord, we need to support backquote ( \`string\` ) syntax and tokenize it as a `Token::SingleQuotedString`

fix: tokenize backquoted strings

---

dump-parser/src/postgres/mod.rs
replibyte/src/source/postgres.rs

Tokenizes `"columnName"` into `Word{value: "columnName", quote_style='"'}` in pgsql driver
fixes #81

fix: tokenize escaped words

---

replibyte/src/config.rs

Makes the source connection_uri optional so it's not required anymore to have it in the configuration file which can be convenient when we already have a dump file.
This PR and this fix https://github.com/Qovery/Replibyte/pull/99 makes it now more clearer to understand what parameters are required.
Let me know if you're OK with this change @evoxmusic :)
Closes #98

fix: make the source connection URI optional

---

website/docs/transformers.md

Hello,
This link is broken 
I guess the idea is to redirect the reader to the section at the bottom of the page. But, maybe consider redirecting the user to the guide in question (`/docs/advanced-guides/web-assembly-transformer`) would be better.

docs: Transformers - Update broken link

---

.gitignore
examples/with-local-disk-datastore.yaml
replibyte/src/cli.rs
replibyte/src/config.rs
replibyte/src/datastore/local_disk.rs
replibyte/src/datastore/mod.rs
replibyte/src/datastore/s3.rs
replibyte/src/main.rs
website/docs/datastores.mdx

This PR adds a new local_disk datastore which stores the dump on the local filesystem.
The datastore configuration follows this format:
```sh
datastore:
local_disk:
dir: ./my-datastore # this directory should exists and needs to be writable and readable
```
It's a work in progress, it miss the following things for now.
Closes #83

Feat: add local disk datastore

---

.github/workflows/on-release.yml

@evoxmusic 
This should fix the automatic modification of the `sha256sum` field in the homebrew Formula.

fix: modify sha256sum correctly on homebrew release

---

.github/workflows/publish-image.yaml
Dockerfile
website/docs/guides/deploy-replibyte/container.md

Closes #97 
- create a Github Actions workflow `publish-image` to build, tag, and push a Docker image based on the [root-level Dockerfile](https://github.com/Qovery/Replibyte/blob/main/Dockerfile)
- workflow only runs when a Github release is published (same as how the [binaries are currently released](https://github.com/Qovery/Replibyte/blob/b673d7a2aa5a3dfbb89cfec9cf4911b5199311b7/.github/workflows/on-release.yml#L1-L4))
- image is pushed to Github Container Registry (`ghcr.io`) with the following tags
- `latest`
- if the release tag is `v<version>`, there will also be a tag `replibyte:<version>` (without the `v`)
- Updated the documentation on running Replibyte as a container to use the published image, instead of building a custom image
I tested an [almost identical …

feat: publish official replibyte container image to Github Packages

---

Cargo.lock
replibyte/Cargo.toml
replibyte/src/config.rs

Hi @evoxmusic, small `pr` to fix #120 and allow usernames with special chars (e.g `@`). 
Thanks and happy birthday!!

Fix #120, decode username to allow users special chars

---

.gitignore
release.sh

@evoxmusic I've added a check before creating and pushing the tag.
If the version in the replibyte Cargo.toml file doesn't contain the right version, I delete the release branch from local and remote repository to rollback.

chore: improve release script by checking if the pull request is merged

---

.github/workflows/on-release.yml

@evoxmusic 
I found 3 potential bugs:
- The key `needs` received an array of names instead of just one name, so accessing it by `needs.build-mac` probably caused undefined behavior - **FIX: Changed from from array to one name**
- Because this action had 2 triggers (`published` and `created`), it was **always** triggered 2 times, and the sha256sum in the downloads was the one of the _first_ trigger, while the _second_ trigger caused a new sha256sum to be generated and replace the one in the Formula, even though the one in the downloads was NOT replaced. This caused a mismatch between the sha256sum values - **FIX: Changed from 2 triggers to a single trigger: `published`**
- Extracting the sha256sum value by using the `$ {{  ... }}` syntax caused an empty value to appear instead of the …

fix: correctly modify sha256 on homebrew action

---

replibyte/src/datastore/local_disk.rs

@evoxmusic 
As we discussed on Discord, this is the PR that fix the `test_delete_keep_last` test. Finally, I've used a helper function tu update the `created_at` field after creating the dump so we don't need to slow down the tests by adding a sleep.

fix test_delete_keep_last

---

dump-parser/src/mysql/mod.rs
replibyte/src/source/mysql.rs
replibyte/src/source/postgres.rs
replibyte/src/transformer/mod.rs

hi @evoxmusic 
This PR fixes transformations of MySQL columns by correctly parsing the table name as a single quoted string token.
I have equally change how the skip config is handled to simplify, now it's directly parsed and passed in the `mysqldump` args so we don't need to handle it manually anymore. See https://github.com/Qovery/Replibyte/compare/main...fabriceclementz:fix-transformers-for-mysql?expand=1#diff-779da9398d8444388b74dd3391171530e14248d77cf4e4526eb66b901695079fR95
Closes #143

fix: get table by getting a single quoted string token

---

website/docs/getting-started/installation.mdx

Hi @evoxmusic 
This PR updates the installation guide with Docker.
I think this could take off some friction out of using RepliByte with Docker.
See #147

docs: update the installation docker guide to use the official RepliByte image

---

Cargo.lock
replibyte/src/commands/dump.rs
replibyte/src/config.rs
replibyte/src/datastore/local_disk.rs
replibyte/src/destination/mongodb.rs
replibyte/src/source/mongodb.rs
replibyte/src/telemetry.rs
website/docs/contributing.md
website/docs/guides/1-create-a-dump.md

This PR has a few changes, but includes primarily the functionality to pass the mongo URI directly to mongosh and mongodump/mongorestore.
This also includes moving from `mongo` to `mongosh`, as the former is deprecated.
Should resolve issue #135

feat: atlas support

---

replibyte/src/destination/postgres.rs

This PR fixes an issue when wiping the public schema for a username that needed tokenization

fix: tokenize username in database wipe

---

examples/replibyte.yaml
replibyte/src/commands/dump.rs
replibyte/src/config.rs
website/docs/guides/2-restore-a-dump.md

This pr had the ability, for a user, to disable the public schema wipe, that was done by default.
In our case, we didn't want to touch the public schema
This is a non-breaking change

feat(destination): add ability to disable schema wipe

---

replibyte/src/commands/dump.rs
replibyte/src/config.rs
replibyte/src/destination/mongodb.rs
replibyte/src/source/mongodb.rs
replibyte/src/telemetry.rs

Hi @evoxmusic 
This PR https://github.com/Qovery/Replibyte/pull/154 makes a change in the different mongo commands to use the `--uri` option and pass the connection string directly so we no longer need to pass the `--authenticationDatabase` option as the authSource is directly included in the uri.
As stated in this issue/comment  https://github.com/Qovery/Replibyte/issues/147#issuecomment-1149945859 it even introduces an error (depending on the mongodump/mongorestore you're using I guess)

fix(mongo): remove the '--authenticationDatabase' option from mongo commands as we pass the '--uri' option

---

examples/wasm/README.md

The previous URL had a typo, and resulted in a 404 page.

Fix typo in the URL

---

replibyte/src/source/mysql.rs

We use UUIDs as BINARY(16) primary keys, without `--hex-blob` I get a UTF8Error when dumping.
Not sure if there are any downsides to adding this though.

Add `--hex-blob` to mysqldump

---

replibyte/src/source/postgres.rs
replibyte/src/transformer/mod.rs

Wrap table name to qoutes when creating transformers map for PostgreSQL (#174)

---

dump-parser/src/mysql/mod.rs

Hello,
This PR will prevent panic when a MySQL table has a `COMMENT`. I have update the `tokenizer_for_create_table_query` test function by updating the create table statement with additional comments on field and table.

fix(mysql): prevent panic when table has comment

---

dump-parser/src/mysql/mod.rs
dump-parser/src/postgres/mod.rs
dump-parser/src/utils.rs

A number of fixes to unblock our use cases.
These should potentially fix a number of open issues.
1. Single quoted tests containing a quote were broken, as a result parsing was broken on our MySQL dumps.
2. Single quoted string tokenization containing -- was broken.
3. 30MB MySQL dump would do not finish in 30minutes due to slow fallback for utf8 strings with multibyte characters.
Best to review each commit separately.
d68a435 - Potentially fixes #124, #169, as well as incorrect escaped quote parsing, which would cascade to other issues.
29bba0a - Potentially fixes #200, #189, #184, #92 as from the brief look the slow path is O(c<sup>n</sup>). 
I have not run integration tests, as I don't have docker on the current machine.

Fixes a number of sql parser bugs

---

replibyte/src/datastore/s3.rs

get_bucket_accelerate_configuration will return `MethodNotAllowed` (anyway, I encountered this error), so exists check always failed.
change to `list_buckets` and iterate to check if the bucket name already exists

feat: use list_buckets check bucket exists

---

Dockerfile

Currently using rust:1.59-slim-buster, under my M1 mac the image size is up to 
```bash
rust 1.59-slim-buster 9e6a443fa584 4 months ago 813MB
```
after changing to debain:cluster-slim
```bash
debian buster-slim 10fbfaf982d2 2 weeks ago 63.5MB
```
Expected to save about 10 times.

chore: use debain buster slim optimize image size

---

dump-parser/src/utils.rs

Fixes #220
Utf-8 parse errors affect users, and given the choice between panicking and skipping a query, the latter seems like the better option.
There might be a third option I'm not seeing though. Let me know if you prefer to solve this another way 👍

fix: Add utf-8 parsing error handling

---

website/docs/guides/deploy-replibyte/container.md

Looks like the warning banner has a typo

Correct filename

---

replibyte/src/transformer/redacted.rs

fix #275 
Hi @evoxmusic, this address the issue on indexing over values that can contains multi-byte chars. 
Thx!

fix: handle multi-byte chars on redacted transformer
