Qovery/Replibyte

Cargo.lock
README.md
replibyte/Cargo.toml
replibyte/src/bridge/mod.rs
replibyte/src/bridge/s3.rs
replibyte/src/config.rs
replibyte/src/database.rs
replibyte/src/main.rs
replibyte/src/source/postgres.rs
replibyte/src/tasks.rs
replibyte/src/transformer.rs
replibyte/src/transformer/mod.rs
replibyte/src/transformer/random.rs
replibyte/src/transformer/transient.rs
replibyte/src/types.rs

feat: source data s3 upload

---

.gitignore
Cargo.lock
Cargo.toml
replibyte/Cargo.toml
replibyte/README.md
replibyte/src/bridge/mod.rs
replibyte/src/bridge/s3.rs
replibyte/src/main.rs
replibyte/src/transformer/mod.rs
replibyte/src/transformer/random.rs
replibyte/src/transformer/transient.rs

- Added configuration files to the `.gitignore`
- Cleaned up some code and made minor patches
- Updated the formatting in the workspace-level `Cargo.toml`
- Updated AWS Rust SDK component versions from `0.8` to `0.9`
- Started using `anyhow::Result<()>` instead of `Result<(), Error>` in some parts of the code

chore: Minor updates

---

README.md

The documentation was somewhat unclear and I have decided to revamp it a bit. For a quick follow-up, you can check out [our chat on Qovery's Discord Server](https://discord.com/channels/688766934917185556/952516115039408168/954243345784377365).

docs: Updated the documentation

---

Cargo.lock
README.md
TRANSFORMERS.md
replibyte/Cargo.toml
replibyte/src/config.rs
replibyte/src/transformer/first_name.rs
replibyte/src/transformer/mod.rs

Hi,
I've added an implementation for the first-name transformer. 
For generating the first name, I've added the https://github.com/cksac/fake-rs library because I thought it could equally be helpful for other transformers ?

feat: add a first name transformer

---

.github/workflows/build-and-test.yml
replibyte/src/bridge/s3.rs

make tests pass

---

README.md
TRANSFORMERS.md
replibyte/src/config.rs
replibyte/src/transformer/keep_first_char.rs
replibyte/src/transformer/mod.rs

feat: add the keep first character transformer

---

README.md
TRANSFORMERS.md
replibyte/src/config.rs
replibyte/src/transformer/mod.rs
replibyte/src/transformer/phone_number.rs

@evoxmusic the phone number transformer is ready to merge. At some point, I think I will try to add a locale options later (FR, EN...) It would be great !

feat: add a phone number transformer

---

examples/source-postgres-with-skip.yaml
replibyte/src/config.rs
replibyte/src/main.rs
replibyte/src/source/mod.rs
replibyte/src/source/postgres.rs
replibyte/src/source/postgres_stdin.rs
replibyte/src/tasks/full_backup.rs

Hi @evoxmusic 
I'm trying to resolve #18. At first, I would have adding `--exclude-table=` parameters according to this documentation https://www.postgresql.org/docs/9.3/app-pgdump.html  but It seems we can't with `pg_dumpall` as the name suggests.
So I'm trying to exclude rows during the stream reading.
Let me now, if you would have implemented this way.
----

feat : skip tables

---

TRANSFORMERS.md
replibyte/src/config.rs
replibyte/src/transformer/credit_card.rs
replibyte/src/transformer/mod.rs

Hi @evoxmusic 
This is a basic Credit card transformer based on fake-rs, you're free to merge :)

feat: add credit card transformer

---

.github/workflows/build-and-test.yml
dump-parser/src/mongodb/mod.rs
dump-parser/src/utils.rs
replibyte/src/source/mongodb.rs

fix: mongodb source

---

Cargo.lock
README.md
replibyte/Cargo.toml
replibyte/src/cli.rs
replibyte/src/destination/docker.rs
replibyte/src/destination/mod.rs
replibyte/src/destination/mongodb_docker.rs
replibyte/src/destination/postgres_docker.rs
replibyte/src/main.rs
replibyte/src/tasks/full_restore.rs

This PR add support for restoring a backup inside a Docker container as discussed in #32.
> This is currently a wip, needs some tests and improvements
Closes #32

feat: restore backup in local container

---

replibyte/src/commands/backup.rs
replibyte/src/commands/mod.rs
replibyte/src/commands/restore.rs
replibyte/src/commands/transformer.rs
replibyte/src/main.rs

Hello @evoxmusic 
This PR extracts commands from the main file to improve readability. There is no bug fix or new feature.
I have thought it will be simpler to maintain this way for further improvements and fixes.
Let me know what you think, maybe you don't want to accept this PR for now, if so don't hesitate to tell me :)

refactor: extract commands from main

---

.github/workflows/on-release.yml

This should fix the homebrew release action.
edit: I just noticed this action didn't pass in previous releases as well.
Not 100% sure it will fix it, maybe it's a different problem.

fix: homebrew release

---

Dockerfile

This PR adds MySQL binaries and MongoDB tools in the Dockerfile.
You're free to merge @evoxmusic 
Closes #49

fix: add MongoDB tools and MySQL binaries in Dockerfile

---

.github/workflows/on-release.yml

should fix the bug introduced by #59

fix: release on homebrew

---

replibyte/src/source/postgres.rs

@evoxmusic I've replace the `pg_dumpall` command by `pg_dump`
Closes #72

fix: call pg_dump instead of pg_dumpall command

---

replibyte/src/config.rs

Solves #77 
Not sure if this should be implemented only for mysql or other DBs as well
@evoxmusic WDYT?

fix: allow mysql connection to not have password

---

replibyte/src/config.rs

@evoxmusic A little fix before going to sleep 💤 
Closes #84

fix: add 'postgresql' as a valid postgres connection string scheme

---

dump-parser/src/postgres/mod.rs
dump-parser/src/utils.rs

Fix bad SQL dump parsing leading to `Unterminated string literal` error.

fix: Unterminated string literal

---

replibyte/src/config.rs
replibyte/src/datastore/s3.rs
replibyte/src/main.rs
website/docs/datastores.mdx

- Only providing configuration options to override environment
closes #102

fix: Using the default AWS SDK configuration mechanisms (#102)

---

.github/workflows/on-release.yml

This should fix the automatic homebrew release.
I checked it on my fork and it seems to be working okay.
Also, loosely related to #56

fix: homebrew release action

---

website/docs/transformers.md

This PR adds the documentation for using the transformers on nested fields.

chore: add transformers nested fields documentation

---

replibyte/src/cli.rs
replibyte/src/commands/dump.rs

This is to address https://github.com/Qovery/Replibyte/issues/100.

feat: allow MongoDB import from stdin

---

replibyte/src/commands/dump.rs
replibyte/src/config.rs
replibyte/src/telemetry.rs

This PR just makes transformers optional.
Closes #119

fix: make transformers optional

---

Cargo.lock
dump-parser/Cargo.toml
replibyte/Cargo.toml
replibyte/src/source/postgres.rs
subset/Cargo.toml

Release v0.8.1

---

dump-parser/Cargo.toml
replibyte/Cargo.toml
subset/Cargo.toml

Release v0.8.2

---

replibyte/src/migration/mod.rs

Hello @evoxmusic 
An error is actually triggered when running RepliByte for the first time if you don't have an existing metadata.json file.
This PR fix it by skipping migrations as we don't need do running them if we don't have a metadata.json file.

fix: skip running migrate when there is no metadata.json file

---

Cargo.lock
dump-parser/Cargo.toml
replibyte/Cargo.toml
subset/Cargo.toml

Release v0.8.3

---

dump-parser/Cargo.toml
replibyte/Cargo.toml
subset/Cargo.toml

Release v0.8.4

---

Cargo.lock
dump-parser/Cargo.toml
replibyte/Cargo.toml
subset/Cargo.toml

Release v0.8.5

---

Cargo.lock
dump-parser/Cargo.toml
replibyte/Cargo.toml
subset/Cargo.toml

Release v0.8.6

---

dump-parser/Cargo.toml
replibyte/Cargo.toml
subset/Cargo.toml

Release v0.9.1

---

website/docs/datastores.mdx

Added example permissions based on what I'm using in AWS.

fix(docs): adding example s3 permissions for iam user

---

replibyte/src/commands/dump.rs
replibyte/src/config.rs
replibyte/src/source/mod.rs
replibyte/src/source/mongodb.rs
replibyte/src/source/mysql.rs
replibyte/src/source/postgres.rs
website/docs/getting-started/configuration.md

Add options to dump specific tables (#150)

---

dump-parser/Cargo.toml
replibyte/Cargo.toml
subset/Cargo.toml

Release v0.9.2

---

replibyte/src/destination/mysql.rs

Add database argument to mysql restore dump command (#191)

---

dump-parser/Cargo.toml
replibyte/Cargo.toml
subset/Cargo.toml

Release v0.9.3

---

dump-parser/src/utils.rs

Fixes https://github.com/Qovery/Replibyte/issues/180

Fix escape quote check

---

dump-parser/Cargo.toml
replibyte/Cargo.toml
subset/Cargo.toml

Release v0.9.4

---

dump-parser/Cargo.toml
replibyte/Cargo.toml
subset/Cargo.toml

Release v0.9.5

---

dump-parser/Cargo.toml
replibyte/Cargo.toml
subset/Cargo.toml

Release v0.9.6

---

dump-parser/Cargo.toml
replibyte/Cargo.toml
subset/Cargo.toml

Release v0.9.7

---

dump-parser/Cargo.toml
replibyte/Cargo.toml
subset/Cargo.toml

Release v0.10.0
